language: cpp
compiler: g++
os: linux
before_install:
        - mkdir build && cd tests && mkdir build;
script:
        - cd build && cmake .. && make;
        - cd ../tests/build && cmake .. && make && ./FunctionFromStringTest;
notifications:
        email:false
branches:
        only:
                - configure_travis
